### ISSUE TITLE
Get individual params value with respect to name

### ISSUE THREAD

**Issue by crypt0inf0** [mingjingc/abi-decoder#1]
Hi, How to get values of params name ie. `method.Params._addr` returns the value `0x839C6f5a014cbfA319e8fDFA01AaC186638945A8`

right now it outputs,
```
{_name 小明 string}
{_age 120000000000000000000000000000000000000 uint256}
{_addr 0x839C6f5a014cbfA319e8fDFA01AaC186638945A8 address}
```

Can we get the individual values out of it?

**Comment by mingjingc** [comment]
param name maybe empty, so we cannot get param value by param name.

**Comment by mingjingc** [comment]
> Hi, How to get values of params name ie. `method.Params._addr` returns the value `0x839C6f5a014cbfA319e8fDFA01AaC186638945A8`
> 
> right now it outputs,
> 
> ```
> {_name 小明 string}
> {_age 120000000000000000000000000000000000000 uint256}
> {_addr 0x839C6f5a014cbfA319e8fDFA01AaC186638945A8 address}
> ```
> 
> Can we get the individual values out of it?

param name maybe empty, so we cannot get param value by param name.

**Comment by mingjingc** [comment]
> Hi, How to get values of params name ie. `method.Params._addr` returns the value `0x839C6f5a014cbfA319e8fDFA01AaC186638945A8`
> 
> right now it outputs,
> 
> ```
> {_name 小明 string}
> {_age 120000000000000000000000000000000000000 uint256}
> {_addr 0x839C6f5a014cbfA319e8fDFA01AaC186638945A8 address}
> ```
> 
> Can we get the individual values out of it?
